services:
  - type: web
    name: metabit-safety
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT & python run_telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: metabit-safety-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: metabit-safety-db
    databaseName: metabit_safety
    user: metabit_safety_user
