services:
  - type: web
    name: metabit-safety
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: metabit-safety-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  - name: metabit-safety-db
    databaseName: metabit_safety
    user: metabit_safety_user
