services:
  - type: web
    name: metabit-safety
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: metabit-safety-db
          property: connectionString
      - key: PORT
        value: 10000

  - type: worker
    name: metabit-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: metabit-safety-db
          property: connectionString

databases:
  - name: metabit-safety-db
    databaseName: metabit_safety
    user: metabit_safety_user
