services:
  - type: web
    name: metabit-safety
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: metabit-safety-db
          property: connectionString

databases:
  - name: metabit-safety-db
    databaseName: metabit_safety
    user: metabit_safety_user
