services:
  - type: web
    name: metabit-safety
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://metabit_safty_v2_user:XQOseF8u3nOdICnP2Ko8LcUMx7hI49TO@dpg-d01a2b3e5dus73e1rbi0-a.singapore-postgres.render.com/metabit_safty_v2
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        value: 8093639537:AAEGVJfZi1hFkv-iSiJWruGB2SYssfYJfvY
      - key: WEB_CONCURRENCY
        value: 2
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: false
      - key: FLASK_APP
        value: app.py

databases:
  - name: metabit-safety-db
    databaseName: metabit_safety
    user: metabit_safety_user
    plan: free
