services:
  - type: web
    name: metabit-safety
    env: python
    buildCommand: ./build.sh
<<<<<<< HEAD
    startCommand: ./start.sh
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://metabit_safty_db_user:i7jQbcMMM2sg7k12PwweDO1koIUd3ppF@dpg-cvc9e8bv2p9s73ad9g5g-a.singapore-postgres.render.com/metabit_safty_db
      - key: PORT
        value: 10000
      - key: TELEGRAM_BOT_TOKEN
        value: 8093639537:AAEGVJfZi1hFkv-iSiJWruGB2SYssfYJfvY
      - key: WEB_CONCURRENCY
        value: 2
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: false
      - key: FLASK_APP
        value: app.py
=======
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: metabit-safety-db
          property: connectionString
>>>>>>> 0b2e9edf5d191e0912dd4d125ab7926541c65858

databases:
  - name: metabit-safety-db
    databaseName: metabit_safety
    user: metabit_safety_user
<<<<<<< HEAD
    plan: free
=======
>>>>>>> 0b2e9edf5d191e0912dd4d125ab7926541c65858
